/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 piso3_fisi_final.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Piso3(props) {
  const { nodes, materials } = useGLTF('/piso3_fisi_final.glb')

  if(props.isView == false){
    return null   
  }  

  return (
    <group {...props} dispose={null}>
      <group position={[-14.857, 0, -17.978]}>
        <mesh geometry={nodes.CTRL_Baseboard030.geometry} material={materials['hidden_material.026']} position={[0, -0.1, 0.177]} />
        <mesh geometry={nodes.CTRL_Hole030.geometry} material={materials['hidden_material.026']} position={[0, -0.002, 0.12]} />
        <mesh geometry={nodes.DoorFrame030.geometry} material={materials['Door_material.027']}>
          <mesh geometry={nodes.Door030.geometry} material={materials['Door_material.027']} position={[0.418, 1.05, 0.022]}>
            <mesh geometry={nodes.Handle_Back029.geometry} material={materials['Handle_material.025']} position={[-0.764, 0, -0.005]} />
            <mesh geometry={nodes.Handle_Front029.geometry} material={materials['Handle_material.025']} position={[-0.764, 0, -0.029]} rotation={[-Math.PI, 0, 0]} />
          </mesh>
        </mesh>
      </group>
      <group position={[-13.856, 0, -18]}>
        <mesh geometry={nodes.CTRL_Baseboard029.geometry} material={materials['hidden_material.025']} position={[0, -0.1, 0.177]} />
        <mesh geometry={nodes.CTRL_Hole029.geometry} material={materials['hidden_material.025']} position={[0, -0.002, 0.12]} />
        <mesh geometry={nodes.DoorFrame029.geometry} material={materials['Door_material.026']}>
          <mesh geometry={nodes.Door029.geometry} material={materials['Door_material.026']} position={[0.418, 1.05, 0.022]}>
            <mesh geometry={nodes.Handle_Back028.geometry} material={materials['Handle_material.024']} position={[-0.764, 0, -0.005]} />
            <mesh geometry={nodes.Handle_Front028.geometry} material={materials['Handle_material.024']} position={[-0.764, 0, -0.029]} rotation={[-Math.PI, 0, 0]} />
          </mesh>
        </mesh>
      </group>
      <group position={[-12.841, 0, -18.02]}>
        <mesh geometry={nodes.CTRL_Baseboard028.geometry} material={materials['hidden_material.024']} position={[0, -0.1, 0.177]} />
        <mesh geometry={nodes.CTRL_Hole028.geometry} material={materials['hidden_material.024']} position={[0, -0.002, 0.12]} />
        <mesh geometry={nodes.DoorFrame028.geometry} material={materials['Door_material.025']}>
          <mesh geometry={nodes.Door028.geometry} material={materials['Door_material.025']} position={[0.418, 1.05, 0.022]}>
            <mesh geometry={nodes.Handle_Back027.geometry} material={materials['Handle_material.023']} position={[-0.764, 0, -0.005]} />
            <mesh geometry={nodes.Handle_Front027.geometry} material={materials['Handle_material.023']} position={[-0.764, 0, -0.029]} rotation={[-Math.PI, 0, 0]} />
          </mesh>
        </mesh>
      </group>
      <group position={[15.376, 0, 24.584]}>
        <mesh geometry={nodes.CTRL_Baseboard024.geometry} material={materials['hidden_material.020']} position={[0, -0.1, 0.177]} />
        <mesh geometry={nodes.CTRL_Hole024.geometry} material={materials['hidden_material.020']} position={[0, -0.002, 0.12]} />
        <mesh geometry={nodes.DoorFrame024.geometry} material={materials['Door_material.021']}>
          <mesh geometry={nodes.Door024.geometry} material={materials['Door_material.021']} position={[0.418, 1.05, 0.022]}>
            <mesh geometry={nodes.Handle_Back023.geometry} material={materials['Handle_material.019']} position={[-0.764, 0, -0.005]} />
            <mesh geometry={nodes.Handle_Front023.geometry} material={materials['Handle_material.019']} position={[-0.764, 0, -0.029]} rotation={[-Math.PI, 0, 0]} />
          </mesh>
        </mesh>
      </group>
      <group position={[21.325, 0, 24.585]}>
        <mesh geometry={nodes.CTRL_Baseboard023.geometry} material={materials['hidden_material.019']} position={[0, -0.1, 0.177]} />
        <mesh geometry={nodes.CTRL_Hole023.geometry} material={materials['hidden_material.019']} position={[0, -0.002, 0.12]} />
        <mesh geometry={nodes.DoorFrame023.geometry} material={materials['Door_material.020']}>
          <mesh geometry={nodes.Door023.geometry} material={materials['Door_material.020']} position={[0.418, 1.05, 0.022]}>
            <mesh geometry={nodes.Handle_Back022.geometry} material={materials['Handle_material.018']} position={[-0.764, 0, -0.005]} />
            <mesh geometry={nodes.Handle_Front022.geometry} material={materials['Handle_material.018']} position={[-0.764, 0, -0.029]} rotation={[-Math.PI, 0, 0]} />
          </mesh>
        </mesh>
      </group>
      <group position={[41.839, 0, 24.57]}>
        <mesh geometry={nodes.CTRL_Baseboard017.geometry} material={materials['hidden_material.033']} position={[0, -0.1, 0.177]} />
        <mesh geometry={nodes.CTRL_Hole017.geometry} material={materials['hidden_material.033']} position={[0, -0.002, 0.12]} />
        <mesh geometry={nodes.DoorFrame017.geometry} material={materials['Door_material.034']}>
          <mesh geometry={nodes.Door017.geometry} material={materials['Door_material.034']} position={[0.418, 1.05, 0.022]}>
            <mesh geometry={nodes.Handle_Back016.geometry} material={materials['Handle_material.032']} position={[-0.764, 0, -0.005]} />
            <mesh geometry={nodes.Handle_Front016.geometry} material={materials['Handle_material.032']} position={[-0.764, 0, -0.029]} rotation={[-Math.PI, 0, 0]} />
          </mesh>
        </mesh>
      </group>
      <group position={[-25.18, 0, 23.713]} rotation={[0, Math.PI / 2, 0]}>
        <mesh geometry={nodes.CTRL_Baseboard014.geometry} material={materials['hidden_material.010']} position={[0, -0.1, 0.177]} />
        <mesh geometry={nodes.CTRL_Hole014.geometry} material={materials['hidden_material.010']} position={[0, -0.002, 0.12]} />
        <mesh geometry={nodes.DoorFrame014.geometry} material={materials['Door_material.011']}>
          <mesh geometry={nodes.Door014.geometry} material={materials['Door_material.011']} position={[0.418, 1.05, 0.022]}>
            <mesh geometry={nodes.Handle_Back013.geometry} material={materials['Handle_material.009']} position={[-0.764, 0, -0.005]} />
            <mesh geometry={nodes.Handle_Front013.geometry} material={materials['Handle_material.009']} position={[-0.764, 0, -0.029]} rotation={[-Math.PI, 0, 0]} />
          </mesh>
        </mesh>
      </group>
      <group position={[-3.224, 0, -22.584]}>
        <mesh geometry={nodes.CTRL_Baseboard013.geometry} material={materials['hidden_material.009']} position={[0, -0.1, 0.177]} />
        <mesh geometry={nodes.CTRL_Hole013.geometry} material={materials['hidden_material.009']} position={[0, -0.002, 0.12]} />
        <mesh geometry={nodes.DoorFrame013.geometry} material={materials['Door_material.010']}>
          <mesh geometry={nodes.Door013.geometry} material={materials['Door_material.010']} position={[0.418, 1.05, 0.022]}>
            <mesh geometry={nodes.Handle_Back012.geometry} material={materials['Handle_material.008']} position={[-0.764, 0, -0.005]} />
            <mesh geometry={nodes.Handle_Front012.geometry} material={materials['Handle_material.008']} position={[-0.764, 0, -0.029]} rotation={[-Math.PI, 0, 0]} />
          </mesh>
        </mesh>
      </group>
      <group position={[-6.436, 0, -22.602]}>
        <mesh geometry={nodes.CTRL_Baseboard012.geometry} material={materials['hidden_material.008']} position={[0, -0.1, 0.177]} />
        <mesh geometry={nodes.CTRL_Hole012.geometry} material={materials['hidden_material.008']} position={[0, -0.002, 0.12]} />
        <mesh geometry={nodes.DoorFrame012.geometry} material={materials['Door_material.009']}>
          <mesh geometry={nodes.Door012.geometry} material={materials['Door_material.009']} position={[0.418, 1.05, 0.022]}>
            <mesh geometry={nodes.Handle_Back011.geometry} material={materials['Handle_material.007']} position={[-0.764, 0, -0.005]} />
            <mesh geometry={nodes.Handle_Front011.geometry} material={materials['Handle_material.007']} position={[-0.764, 0, -0.029]} rotation={[-Math.PI, 0, 0]} />
          </mesh>
        </mesh>
      </group>
      <group position={[-25.149, 0, 9.536]} rotation={[0, Math.PI / 2, 0]}>
        <mesh geometry={nodes.CTRL_Baseboard010.geometry} material={materials['hidden_material.006']} position={[0, -0.1, 0.177]} />
        <mesh geometry={nodes.CTRL_Hole010.geometry} material={materials['hidden_material.006']} position={[0, -0.002, 0.12]} />
        <mesh geometry={nodes.DoorFrame010.geometry} material={materials['Door_material.007']}>
          <mesh geometry={nodes.Door010.geometry} material={materials['Door_material.007']} position={[0.418, 1.05, 0.022]}>
            <mesh geometry={nodes.Handle_Back009.geometry} material={materials['Handle_material.005']} position={[-0.764, 0, -0.005]} />
            <mesh geometry={nodes.Handle_Front009.geometry} material={materials['Handle_material.005']} position={[-0.764, 0, -0.029]} rotation={[-Math.PI, 0, 0]} />
          </mesh>
        </mesh>
      </group>
      <group position={[-25.152, 0, 11.976]} rotation={[0, Math.PI / 2, 0]}>
        <mesh geometry={nodes.CTRL_Baseboard009.geometry} material={materials['hidden_material.005']} position={[0, -0.1, 0.177]} />
        <mesh geometry={nodes.CTRL_Hole009.geometry} material={materials['hidden_material.005']} position={[0, -0.002, 0.12]} />
        <mesh geometry={nodes.DoorFrame009.geometry} material={materials['Door_material.006']}>
          <mesh geometry={nodes.Door009.geometry} material={materials['Door_material.006']} position={[0.418, 1.05, 0.022]}>
            <mesh geometry={nodes.Handle_Back008.geometry} material={materials['Handle_material.004']} position={[-0.764, 0, -0.005]} />
            <mesh geometry={nodes.Handle_Front008.geometry} material={materials['Handle_material.004']} position={[-0.764, 0, -0.029]} rotation={[-Math.PI, 0, 0]} />
          </mesh>
        </mesh>
      </group>
      <group position={[35.012, 0, 24.558]}>
        <mesh geometry={nodes.CTRL_Baseboard016.geometry} material={materials['hidden_material.032']} position={[0, -0.1, 0.177]} />
        <mesh geometry={nodes.CTRL_Hole016.geometry} material={materials['hidden_material.032']} position={[0, -0.002, 0.12]} />
        <mesh geometry={nodes.DoorFrame016.geometry} material={materials['Door_material.033']}>
          <mesh geometry={nodes.Door016.geometry} material={materials['Door_material.033']} position={[0.418, 1.05, 0.022]}>
            <mesh geometry={nodes.Handle_Back015.geometry} material={materials['Handle_material.031']} position={[-0.764, 0, -0.005]} />
            <mesh geometry={nodes.Handle_Front015.geometry} material={materials['Handle_material.031']} position={[-0.764, 0, -0.029]} rotation={[-Math.PI, 0, 0]} />
          </mesh>
        </mesh>
      </group>
      <group position={[-25.189, 0, 19.932]} rotation={[0, Math.PI / 2, 0]}>
        <mesh geometry={nodes.CTRL_Baseboard006.geometry} material={materials['hidden_material.002']} position={[0, -0.1, 0.177]} />
        <mesh geometry={nodes.CTRL_Hole006.geometry} material={materials['hidden_material.002']} position={[0, -0.002, 0.12]} />
        <mesh geometry={nodes.DoorFrame006.geometry} material={materials['Door_material.003']}>
          <mesh geometry={nodes.Door006.geometry} material={materials['Door_material.003']} position={[0.418, 1.05, 0.022]}>
            <mesh geometry={nodes.Handle_Back005.geometry} material={materials['Handle_material.001']} position={[-0.764, 0, -0.005]} />
            <mesh geometry={nodes.Handle_Front005.geometry} material={materials['Handle_material.001']} position={[-0.764, 0, -0.029]} rotation={[-Math.PI, 0, 0]} />
          </mesh>
        </mesh>
      </group>
      <group position={[-25.191, 0, 28.455]} rotation={[0, Math.PI / 2, 0]}>
        <mesh geometry={nodes.CTRL_Baseboard005.geometry} material={materials['hidden_material.001']} position={[0, -0.1, 0.177]} />
        <mesh geometry={nodes.CTRL_Hole005.geometry} material={materials['hidden_material.001']} position={[0, -0.002, 0.12]} />
        <mesh geometry={nodes.DoorFrame005.geometry} material={materials['Door_material.002']}>
          <mesh geometry={nodes.Door005.geometry} material={materials['Door_material.002']} position={[0.418, 1.05, 0.022]} />
        </mesh>
      </group>
      <group position={[-25.193, 0, 38.998]} rotation={[0, Math.PI / 2, 0]}>
        <mesh geometry={nodes.CTRL_Baseboard004.geometry} material={materials.hidden_material} position={[0, -0.1, 0.177]} />
        <mesh geometry={nodes.CTRL_Hole004.geometry} material={materials.hidden_material} position={[0, 0, 0.12]} />
        <mesh geometry={nodes.DoorFrame004.geometry} material={materials.Door_material}>
          <mesh geometry={nodes.Door004.geometry} material={materials.Door_material} position={[0.418, 1.05, 0.022]}>
            <mesh geometry={nodes.Handle_Back004.geometry} material={materials.Handle_material} position={[-0.764, 0, -0.005]} />
            <mesh geometry={nodes.Handle_Front004.geometry} material={materials.Handle_material} position={[-0.764, 0, -0.029]} rotation={[-Math.PI, 0, 0]} />
          </mesh>
        </mesh>
      </group>
      <group position={[-2.565, 0, 24.569]}>
        <mesh geometry={nodes.CTRL_Baseboard001.geometry} material={materials['hidden_material.003']} position={[0, -0.1, 0.177]} />
        <mesh geometry={nodes.CTRL_Hole001.geometry} material={materials['hidden_material.003']} position={[0, -0.002, 0.12]} />
        <mesh geometry={nodes.DoorFrame001.geometry} material={materials['Door_material.001']}>
          <mesh geometry={nodes.Door001.geometry} material={materials['Door_material.001']} position={[0.418, 1.05, 0.022]}>
            <mesh geometry={nodes.Handle_Back001.geometry} material={materials['Handle_material.002']} position={[-0.764, 0, -0.005]} />
            <mesh geometry={nodes.Handle_Front001.geometry} material={materials['Handle_material.002']} position={[-0.764, 0, -0.029]} rotation={[-Math.PI, 0, 0]} />
          </mesh>
        </mesh>
      </group>
      <directionalLight intensity={683} decay={2} position={[0, 15, 0]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Text012.geometry} material={materials['Material.013']} position={[-28.474, 4, -28.807]} rotation={[0.803, 0.184, -0.187]} />
      <mesh geometry={nodes.Text011.geometry} material={materials['Material.012']} position={[8.458, 4, -20.948]} rotation={[0.793, -0.123, 0.124]} />
      <mesh geometry={nodes.Text010.geometry} material={materials['Material.011']} position={[-8.24, 3, -18.742]} rotation={[0.803, 0.184, -0.187]} />
      <mesh geometry={nodes.Text009.geometry} material={materials['Material.010']} position={[0.248, 3, 28.497]} rotation={[0.803, -0.184, 0.187]} />
      <mesh geometry={nodes.Text008.geometry} material={materials['Material.009']} position={[39.585, 4, 22.417]} rotation={[0.835, -0.303, 0.319]} />
      <mesh geometry={nodes.Text006.geometry} material={materials['Material.007']} position={[24.696, 5, 21.767]} rotation={[1.005, -0.245, 0.365]} />
      <mesh geometry={nodes.Text005.geometry} material={materials['Material.006']} position={[17.958, 4, 22.511]} rotation={[0.803, -0.184, 0.187]} />
      <mesh geometry={nodes.Text003.geometry} material={materials['Material.004']} position={[-39.338, 5, 40.643]} rotation={[0.803, 0.184, -0.187]} />
      <mesh geometry={nodes.Text002.geometry} material={materials['Material.001']} position={[-27.759, 4, 26.963]} rotation={[0.803, 0.184, -0.187]} />
      <mesh geometry={nodes.Text.geometry} material={materials['Material.002']} position={[-30.899, 3, 12.77]} rotation={[0.803, 0.184, -0.187]} />
      <mesh geometry={nodes.Stairs194.geometry} material={materials['Stairs_material.248']} position={[30.892, 2, 35.552]} />
      <mesh geometry={nodes.Stairs190.geometry} material={materials['Stairs_material.244']} position={[30.906, 1, 37.351]} />
      <mesh geometry={nodes.Stairs189.geometry} material={materials['Stairs_material.243']} position={[30.908, 1.5, 36.44]} />
      <mesh geometry={nodes.Stairs183.geometry} material={materials['Stairs_material.233']} position={[33.677, 0, 35.657]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.Stairs181.geometry} material={materials['Stairs_material.231']} position={[33.682, 0.5, 36.471]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.Stairs170.geometry} material={materials['Stairs_material.212']} position={[-15.827, 1.5, 40.954]} />
      <mesh geometry={nodes.Stairs166.geometry} material={materials['Stairs_material.208']} position={[-15.824, 1, 41.861]} />
      <mesh geometry={nodes.Stairs152.geometry} material={materials['Stairs_material.194']} position={[-24.667, 0.5, 40.994]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.Stairs147.geometry} material={materials['Stairs_material.181']} position={[-26.127, 2, 16.47]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Stairs146.geometry} material={materials['Stairs_material.180']} position={[-27.046, 1.5, 16.47]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Stairs141.geometry} material={materials['Stairs_material.174']} position={[-27.101, 0.5, 17.86]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Stairs140.geometry} material={materials['Stairs_material.173']} position={[-26.196, 0, 17.858]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Stairs139.geometry} material={materials['Stairs_material.190']} position={[-24.666, 0, 40.08]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.Stairs134.geometry} material={materials['Stairs_material.185']} position={[-19.546, 1.5, 40.954]} />
      <mesh geometry={nodes.Stairs131.geometry} material={materials['Stairs_material.164']} position={[-27.971, 1, 16.47]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Stairs123.geometry} material={materials['Stairs_material.156']} position={[-21.305, 0, -26.358]} />
      <mesh geometry={nodes.Stairs117.geometry} material={materials['Stairs_material.150']} position={[-19.949, 1, -28.149]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.Stairs115.geometry} material={materials['Stairs_material.148']} position={[-19.949, 1.5, -27.224]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.Stairs113.geometry} material={materials['Stairs_material.146']} position={[-19.949, 1, -28.149]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.Stairs111.geometry} material={materials['Stairs_material.144']} position={[-19.949, 1.5, -27.224]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.Stairs090.geometry} material={materials['Stairs_material.135']} position={[27.715, 1.5, -27.207]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.Stairs084.geometry} material={materials['Stairs_material.123']} position={[27.715, 1, -28.132]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.Stairs055.geometry} material={materials['Stairs_material.114']} position={[26.36, 0.5, -27.259]} />
      <mesh geometry={nodes.Stairs052.geometry} material={materials['Stairs_material.113']} position={[26.36, 0, -26.341]} />
      <mesh geometry={nodes.Room048.geometry} material={materials.Wall_material} position={[-5.092, 0, -22.584]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Room047.geometry} material={materials['Wall_material.001']} position={[-31.351, 0, 10.802]} />
      <mesh geometry={nodes.Room044.geometry} material={materials.Wall_material} position={[36.156, 0, 20.357]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Room043.geometry} material={materials.Wall_material} position={[-12.249, 0, 9.874]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Room042.geometry} material={materials['Wall_material.001']} position={[29.671, 0, 34.308]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Room041.geometry} material={materials.Wall_material} position={[-12.279, 0, 5.327]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <mesh geometry={nodes.Room040.geometry} material={materials.Wall_material} position={[-14.867, 0, 9.802]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Room039.geometry} material={materials.Wall_material} position={[17.76, 0, 20.423]} />
      <mesh geometry={nodes.Room038.geometry} material={materials['Material.020']} position={[29.691, 1, 41.791]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Room037.geometry} material={materials.Wall_material} position={[32.197, 0, 38.916]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Room036.geometry} material={materials.Wall_material} position={[-25.13, 0, 43.639]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Room035.geometry} material={materials.Wall_material} position={[-20.015, 0, 42.265]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Room034.geometry} material={materials['Material.019']} position={[-25.197, 1, 43.605]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Room033.geometry} material={materials['Material.021']} position={[-31.35, 1, 15.333]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Room032.geometry} material={materials.Wall_material} position={[-28.011, 0, 17.1]} />
      <mesh geometry={nodes.Room031.geometry} material={materials['Wall_material.018']} position={[-20.522, 0, -30.531]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh geometry={nodes.Baseboard007.geometry} material={materials['Baseboard_material.002']} />
      </mesh>
      <mesh geometry={nodes.Room030.geometry} material={materials['Wall_material.018']} position={[-24.814, 1, -30.483]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Room029.geometry} material={materials.Wall_material} position={[-20.812, 0, -28.359]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh geometry={nodes.Baseboard004.geometry} material={materials.Baseboard_material} />
      </mesh>
      <mesh geometry={nodes.Room028.geometry} material={materials.Wall_material} position={[26.95, 0, -28.342]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh geometry={nodes.Baseboard003.geometry} material={materials.Baseboard_material} />
      </mesh>
      <mesh geometry={nodes.Room027.geometry} material={materials['Wall_material.001']} position={[22.85, 1, -30.466]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Baseboard008.geometry} material={materials['Baseboard_material.001']} />
      </mesh>
      <mesh geometry={nodes.Room026.geometry} material={materials.Wall_material} position={[27.83, 0, 24.513]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Room025.geometry} material={materials['Wall_material.013']} position={[29.671, 2.4, 34.308]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Room021.geometry} material={materials.Wall_material} position={[29.707, 0, 41.786]} rotation={[0, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Baseboard001.geometry} material={materials.Baseboard_material} />
      </mesh>
      <mesh geometry={nodes.Room020.geometry} material={materials.Wall_material} position={[34.623, 0, 31.506]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Room019.geometry} material={materials.Wall_material} position={[-14.833, 0, 31.548]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Room018.geometry} material={materials.Wall_material} position={[-14.855, 2.4, 20.396]} rotation={[Math.PI, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Room017.geometry} material={materials['Wall_material.009']} position={[-8.586, 0, -22.584]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Room016.geometry} material={materials.Wall_material} position={[-1.267, 0, -22.462]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh geometry={nodes.Baseboard.geometry} material={materials.Baseboard_material} />
      </mesh>
      <mesh geometry={nodes.Room015.geometry} material={materials.Wall_material} position={[-8.51, 0, -18.124]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Room014.geometry} material={materials['Wall_material.006']} position={[-8.586, 0, -22.593]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Room013.geometry} material={materials['Wall_material.001']} position={[27.142, 0, -30.514]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh geometry={nodes.Baseboard002.geometry} material={materials['Baseboard_material.001']} />
      </mesh>
      <mesh geometry={nodes.Room012.geometry} material={materials.Wall_material} position={[31.899, 2.4, -30.645]} rotation={[Math.PI, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Room011.geometry} material={materials.Wall_material} position={[-15.733, 2.4, -30.586]} rotation={[Math.PI, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Room010.geometry} material={materials.Wall_material} position={[-25.161, 2.4, -30.469]} rotation={[Math.PI, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Room009.geometry} material={materials.Wall_material} position={[-25.687, 0, -18.438]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Room007.geometry} material={materials.Wall_material} position={[-31.84, 0, 15.304]} />
      <mesh geometry={nodes.Room006.geometry} material={materials.Wall_material} position={[-25.24, 0, -4.378]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Room005.geometry} material={materials.Wall_material} position={[-25.253, 0, 30.36]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.Room004.geometry} material={materials.Wall_material} position={[-31.488, 0, 10.802]} />
      <mesh geometry={nodes.Room003.geometry} material={materials.Wall_material} position={[-31.243, 0, 36.279]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Room002.geometry} material={materials.Wall_material} position={[-25.224, 0, 43.621]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Room001.geometry} material={materials.Wall_material} position={[-42.551, 0, 36.26]} />
      <mesh geometry={nodes.Room.geometry} material={materials.Wall_material} position={[-42.1, 0, 43.583]} />
      <mesh geometry={nodes.Room008.geometry} material={materials.Wall_material} position={[-31.367, 0, 21.179]} />
      <mesh geometry={nodes.Room022.geometry} material={materials.Wall_material} position={[-31.337, 0, 25.662]} />
      <mesh geometry={nodes.Room023.geometry} material={materials.Wall_material} position={[20.381, 0, 24.537]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Room024.geometry} material={materials.Wall_material} position={[14.731, 0, 24.537]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Room045.geometry} material={materials.Wall_material} position={[-1.415, 0, 24.545]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Room046.geometry} material={materials.Wall_material} position={[-7.982, 0, 24.525]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Room049.geometry} material={materials.Wall_material} position={[-31.976, 0, -30.5]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Text004.geometry} material={materials['Material.015']} position={[31.419, 4, 22.744]} rotation={[0.835, -0.303, 0.319]} />
      <mesh geometry={nodes.Text007.geometry} material={materials['Material.016']} position={[-4.921, 4, 22.511]} rotation={[0.803, -0.184, 0.187]} />
      <mesh geometry={nodes.Text001.geometry} material={materials['Material.017']} position={[-28.127, 4, 22.444]} rotation={[0.803, 0.184, -0.187]} />
      <mesh geometry={nodes.Text013.geometry} material={materials['Material.018']} position={[-27.954, 4, 19.848]} rotation={[0.803, 0.184, -0.187]} />
      <mesh geometry={nodes.Stairs001.geometry} material={materials['Stairs_material.001']} position={[-16.603, 1.5, 40.954]} />
      <mesh geometry={nodes.Stairs002.geometry} material={materials['Stairs_material.002']} position={[-16.6, 1, 41.861]} />
      <mesh geometry={nodes.Stairs003.geometry} material={materials['Stairs_material.003']} position={[-17.329, 1, 41.861]} />
      <mesh geometry={nodes.Stairs004.geometry} material={materials['Stairs_material.004']} position={[-17.332, 1.5, 40.954]} />
      <mesh geometry={nodes.Stairs005.geometry} material={materials['Stairs_material.005']} position={[-18.014, 1.5, 40.954]} />
      <mesh geometry={nodes.Stairs006.geometry} material={materials['Stairs_material.006']} position={[-18.011, 1, 41.861]} />
      <mesh geometry={nodes.Stairs007.geometry} material={materials['Stairs_material.007']} position={[-18.669, 1, 41.861]} />
      <mesh geometry={nodes.Stairs008.geometry} material={materials['Stairs_material.008']} position={[-18.672, 1.5, 40.954]} />
      <mesh geometry={nodes.Stairs009.geometry} material={materials['Stairs_material.009']} position={[-19.542, 1.5, 40.954]} />
      <mesh geometry={nodes.Stairs010.geometry} material={materials['Stairs_material.010']} position={[-19.539, 1, 41.861]} />
      <mesh geometry={nodes.Stairs011.geometry} material={materials['Stairs_material.011']} position={[-23.914, 0.5, 40.994]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.Stairs012.geometry} material={materials['Stairs_material.012']} position={[-23.913, 0, 40.08]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.Stairs013.geometry} material={materials['Stairs_material.013']} position={[-23.255, 0, 40.08]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.Stairs014.geometry} material={materials['Stairs_material.014']} position={[-23.256, 0.5, 40.994]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.Stairs015.geometry} material={materials['Stairs_material.015']} position={[-22.621, 0.5, 40.994]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.Stairs016.geometry} material={materials['Stairs_material.016']} position={[-22.62, 0, 40.08]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.Stairs017.geometry} material={materials['Stairs_material.017']} position={[-22.008, 0, 40.08]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.Stairs018.geometry} material={materials['Stairs_material.018']} position={[-22.01, 0.5, 40.994]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.Stairs019.geometry} material={materials['Stairs_material.019']} position={[-21.304, 0.5, 40.994]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.Stairs020.geometry} material={materials['Stairs_material.020']} position={[-21.303, 0, 40.08]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.Stairs021.geometry} material={materials['Stairs_material.021']} position={[-20.762, 0, 40.08]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.Stairs022.geometry} material={materials['Stairs_material.022']} position={[-20.763, 0.5, 40.994]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.Stairs023.geometry} material={materials['Stairs_material.023']} position={[-22.049, 0, -26.358]} />
      <mesh geometry={nodes.Stairs024.geometry} material={materials['Stairs_material.024']} position={[-22.049, 0.5, -27.276]} />
      <mesh geometry={nodes.Stairs026.geometry} material={materials['Stairs_material.025']} position={[-22.774, 0.5, -27.276]} />
      <mesh geometry={nodes.Stairs027.geometry} material={materials['Stairs_material.026']} position={[-22.774, 0, -26.358]} />
      <mesh geometry={nodes.Stairs028.geometry} material={materials['Stairs_material.027']} position={[-23.382, 0, -26.358]} />
      <mesh geometry={nodes.Stairs029.geometry} material={materials['Stairs_material.028']} position={[-23.381, 0.5, -27.276]} />
      <mesh geometry={nodes.Stairs030.geometry} material={materials['Stairs_material.029']} position={[-24.224, 0.5, -27.276]} />
      <mesh geometry={nodes.Stairs031.geometry} material={materials['Stairs_material.030']} position={[-24.224, 0, -26.358]} />
      <mesh geometry={nodes.Stairs032.geometry} material={materials['Stairs_material.031']} position={[-19.205, 1, -28.149]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.Stairs033.geometry} material={materials['Stairs_material.032']} position={[-19.205, 1.5, -27.224]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.Stairs039.geometry} material={materials['Stairs_material.037']} position={[-18.656, 1.5, -27.224]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.Stairs043.geometry} material={materials['Stairs_material.039']} position={[-17.892, 1, -28.149]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.Stairs044.geometry} material={materials['Stairs_material.040']} position={[-17.892, 1.5, -27.224]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.Stairs054.geometry} material={materials['Stairs_material.047']} position={[-16.677, 1, -28.149]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.Stairs056.geometry} material={materials['Stairs_material.048']} position={[-16.677, 1.5, -27.224]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.Stairs061.geometry} material={materials['Stairs_material.051']} position={[-21.248, 0.5, -27.276]} />
      <mesh geometry={nodes.Stairs025.geometry} material={materials['Stairs_material.052']} position={[25.683, 0.5, -27.259]} />
      <mesh geometry={nodes.Stairs036.geometry} material={materials['Stairs_material.053']} position={[25.682, 0, -26.341]} />
      <mesh geometry={nodes.Stairs040.geometry} material={materials['Stairs_material.054']} position={[24.836, 0, -26.341]} />
      <mesh geometry={nodes.Stairs042.geometry} material={materials['Stairs_material.055']} position={[24.836, 0.5, -27.259]} />
      <mesh geometry={nodes.Stairs046.geometry} material={materials['Stairs_material.056']} position={[24.159, 0.5, -27.259]} />
      <mesh geometry={nodes.Stairs048.geometry} material={materials['Stairs_material.057']} position={[24.158, 0, -26.341]} />
      <mesh geometry={nodes.Stairs062.geometry} material={materials['Stairs_material.058']} position={[23.679, 0, -26.341]} />
      <mesh geometry={nodes.Stairs063.geometry} material={materials['Stairs_material.059']} position={[23.679, 0.5, -27.259]} />
      <mesh geometry={nodes.Stairs058.geometry} material={materials['Stairs_material.060']} position={[26.666, 0.5, -27.259]} />
      <mesh geometry={nodes.Stairs060.geometry} material={materials['Stairs_material.061']} position={[26.666, 0, -26.341]} />
      <mesh geometry={nodes.Stairs092.geometry} material={materials['Stairs_material.086']} position={[32.684, 0, 35.657]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.Stairs093.geometry} material={materials['Stairs_material.087']} position={[32.689, 0.5, 36.471]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.Stairs094.geometry} material={materials['Stairs_material.088']} position={[29.994, 2, 35.552]} />
      <mesh geometry={nodes.Stairs095.geometry} material={materials['Stairs_material.089']} position={[30.008, 1, 37.351]} />
      <mesh geometry={nodes.Stairs096.geometry} material={materials['Stairs_material.090']} position={[30.01, 1.5, 36.44]} />
      <mesh geometry={nodes.Stairs097.geometry} material={materials['Stairs_material.091']} position={[31.572, 2, 35.552]} />
      <mesh geometry={nodes.Stairs098.geometry} material={materials['Stairs_material.092']} position={[31.587, 1, 37.351]} />
      <mesh geometry={nodes.Stairs099.geometry} material={materials['Stairs_material.093']} position={[31.588, 1.5, 36.44]} />
      <mesh geometry={nodes.Stairs100.geometry} material={materials['Stairs_material.094']} position={[-27.101, 0.5, 17.507]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Stairs101.geometry} material={materials['Stairs_material.095']} position={[-26.196, 0, 17.504]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Stairs102.geometry} material={materials['Stairs_material.096']} position={[-26.127, 2, 15.98]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Stairs103.geometry} material={materials['Stairs_material.097']} position={[-27.046, 1.5, 15.98]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Stairs104.geometry} material={materials['Stairs_material.098']} position={[-27.971, 1, 15.98]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Stairs064.geometry} material={materials['Stairs_material.099']} position={[28.565, 1.5, -27.207]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.Stairs065.geometry} material={materials['Stairs_material.100']} position={[28.565, 1, -28.132]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.Stairs066.geometry} material={materials['Stairs_material.101']} position={[29.227, 1, -28.132]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.Stairs067.geometry} material={materials['Stairs_material.102']} position={[29.227, 1.5, -27.207]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.Stairs068.geometry} material={materials['Stairs_material.103']} position={[29.86, 1.5, -27.207]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.Stairs069.geometry} material={materials['Stairs_material.104']} position={[29.86, 1, -28.132]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.Stairs070.geometry} material={materials['Stairs_material.105']} position={[30.474, 1, -28.132]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.Stairs071.geometry} material={materials['Stairs_material.106']} position={[30.474, 1.5, -27.207]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.Stairs072.geometry} material={materials['Stairs_material.107']} position={[31.051, 1.5, -27.207]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.Stairs073.geometry} material={materials['Stairs_material.117']} position={[31.051, 1, -28.132]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.Stairs034.geometry} material={materials['Stairs_material.118']} position={[-18.362, 1, -28.149]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.Stairs035.geometry} material={materials['Stairs_material.119']} position={[-17.461, 1.5, -27.224]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.Stairs037.geometry} material={materials['Stairs_material.120']} position={[-17.461, 1, -28.149]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.Plane.geometry} material={materials['Material.022']} position={[-0.146, 0, 5.096]} scale={[45, 1, 45]} />
    </group>
  )
}

useGLTF.preload('/piso3_fisi_final.glb')
