/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 piso2_fisi_final.glb 
*/

import React, { useContext, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { MapaContext } from '../pages/MapaContext';

import dijkstra from 'graphology-shortest-path/dijkstra';
import graph2 from '../grafop2'
import point from '../../data/pointsp2.json'
import { RutaMap } from './RutaMap';

export function Piso2(props) {
    const { nodes, materials } = useGLTF('/piso2_fisi_final.glb')

    const {pointAp2,pointBp2} = useContext(MapaContext);
    if(props.isView == false){
        return null
        
    } 
    let pts = [];
    // console.log(pointA,pointB) // parseInt(pointB)
    if(pointAp2 != null && pointBp2 != null){
    const path = dijkstra.bidirectional(
        graph2,
        pointAp2,
        pointBp2,
        'weight'
    );
    // console.log(path);
    
    for (let i=0; i<path.length-1; i++){
        pts.push({a:parseInt(path[i]), b:parseInt(path[i+1]),id:i});
        // console.log(pts)
    }
    }

    return (
        <>
            <group {...props} dispose={null}>
                <group position={[-8.269, 0, -6.244]} scale={[0.487, 1, 0.485]}>
                    <mesh geometry={nodes.CTRL_Baseboard029.geometry} material={materials['hidden_material.025']} position={[0, -0.1, 0.177]} />
                    <mesh geometry={nodes.CTRL_Hole029.geometry} material={materials['hidden_material.025']} position={[0, -0.002, 0.12]} />
                    <mesh geometry={nodes.DoorFrame029.geometry} material={materials['Door_material.026']}>
                    <mesh geometry={nodes.Door029.geometry} material={materials['Door_material.026']} position={[0.418, 1.05, 0.022]}>
                        <mesh geometry={nodes.Handle_Back028.geometry} material={materials['Handle_material.024']} position={[-0.764, 0, -0.005]} />
                        <mesh geometry={nodes.Handle_Front028.geometry} material={materials['Handle_material.024']} position={[-0.764, 0, -0.029]} rotation={[-Math.PI, 0, 0]} />
                    </mesh>
                    </mesh>
                </group>
                <group position={[-7.775, 0, -6.251]} scale={[0.487, 1, 0.485]}>
                    <mesh geometry={nodes.CTRL_Baseboard028.geometry} material={materials['hidden_material.024']} position={[0, -0.1, 0.177]} />
                    <mesh geometry={nodes.CTRL_Hole028.geometry} material={materials['hidden_material.024']} position={[0, -0.002, 0.12]} />
                    <mesh geometry={nodes.DoorFrame028.geometry} material={materials['Door_material.025']}>
                    <mesh geometry={nodes.Door028.geometry} material={materials['Door_material.025']} position={[0.418, 1.05, 0.022]}>
                        <mesh geometry={nodes.Handle_Back027.geometry} material={materials['Handle_material.023']} position={[-0.764, 0, -0.005]} />
                        <mesh geometry={nodes.Handle_Front027.geometry} material={materials['Handle_material.023']} position={[-0.764, 0, -0.029]} rotation={[-Math.PI, 0, 0]} />
                    </mesh>
                    </mesh>
                </group>
        <group position={[6.568, 0, -8.76]} scale={[0.487, 1, 0.485]}>
            <mesh geometry={nodes.CTRL_Baseboard027.geometry} material={materials['hidden_material.023']} position={[0, -0.1, 0.177]} />
            <mesh geometry={nodes.CTRL_Hole027.geometry} material={materials['hidden_material.023']} position={[0, -0.002, 0.12]} />
            <mesh geometry={nodes.DoorFrame027.geometry} material={materials['Door_material.024']}>
            <mesh geometry={nodes.Door027.geometry} material={materials['Door_material.024']} position={[0.418, 1.05, 0.022]}>
                <mesh geometry={nodes.Handle_Back026.geometry} material={materials['Handle_material.022']} position={[-0.764, 0, -0.005]} />
                <mesh geometry={nodes.Handle_Front026.geometry} material={materials['Handle_material.022']} position={[-0.764, 0, -0.029]} rotation={[-Math.PI, 0, 0]} />
            </mesh>
            </mesh>
        </group>
        <group position={[8.362, 0, 14.298]} scale={[0.487, 1, 0.485]}>
            <mesh geometry={nodes.CTRL_Baseboard024.geometry} material={materials['hidden_material.020']} position={[0, -0.1, 0.177]} />
            <mesh geometry={nodes.CTRL_Hole024.geometry} material={materials['hidden_material.020']} position={[0, -0.002, 0.12]} />
            <mesh geometry={nodes.DoorFrame024.geometry} material={materials['Door_material.021']}>
            <mesh geometry={nodes.Door024.geometry} material={materials['Door_material.021']} position={[0.418, 1.05, 0.022]}>
                <mesh geometry={nodes.Handle_Back023.geometry} material={materials['Handle_material.019']} position={[-0.764, 0, -0.005]} />
                <mesh geometry={nodes.Handle_Front023.geometry} material={materials['Handle_material.019']} position={[-0.764, 0, -0.029]} rotation={[-Math.PI, 0, 0]} />
            </mesh>
            </mesh>
        </group>
        <group position={[8.849, 0, 14.298]} scale={[0.487, 1, 0.485]}>
            <mesh geometry={nodes.CTRL_Baseboard023.geometry} material={materials['hidden_material.019']} position={[0, -0.1, 0.177]} />
            <mesh geometry={nodes.CTRL_Hole023.geometry} material={materials['hidden_material.019']} position={[0, -0.002, 0.12]} />
            <mesh geometry={nodes.DoorFrame023.geometry} material={materials['Door_material.020']}>
            <mesh geometry={nodes.Door023.geometry} material={materials['Door_material.020']} position={[0.418, 1.05, 0.022]}>
                <mesh geometry={nodes.Handle_Back022.geometry} material={materials['Handle_material.018']} position={[-0.764, 0, -0.005]} />
                <mesh geometry={nodes.Handle_Front022.geometry} material={materials['Handle_material.018']} position={[-0.764, 0, -0.029]} rotation={[-Math.PI, 0, 0]} />
            </mesh>
            </mesh>
        </group>
        <group position={[-8.529, 0, 0.647]} rotation={[0, Math.PI / 2, 0]} scale={[0.485, 1, 0.487]}>
            <mesh geometry={nodes.CTRL_Baseboard015.geometry} material={materials['hidden_material.011']} position={[0, -0.1, 0.177]} />
            <mesh geometry={nodes.CTRL_Hole015.geometry} material={materials['hidden_material.011']} position={[0, -0.002, 0.12]} />
            <mesh geometry={nodes.DoorFrame015.geometry} material={materials['Door_material.012']}>
            <mesh geometry={nodes.Door015.geometry} material={materials['Door_material.012']} position={[0.418, 1.05, 0.022]}>
                <mesh geometry={nodes.Handle_Back014.geometry} material={materials['Handle_material.010']} position={[-0.764, 0, -0.005]} />
                <mesh geometry={nodes.Handle_Front014.geometry} material={materials['Handle_material.010']} position={[-0.764, 0, -0.029]} rotation={[-Math.PI, 0, 0]} />
            </mesh>
            </mesh>
        </group>
        <group position={[-10.306, 0, 11.241]} scale={[0.487, 1, 0.485]}>
            <mesh geometry={nodes.CTRL_Baseboard014.geometry} material={materials['hidden_material.010']} position={[0, -0.1, 0.177]} />
            <mesh geometry={nodes.CTRL_Hole014.geometry} material={materials['hidden_material.010']} position={[0, -0.002, 0.12]} />
            <mesh geometry={nodes.DoorFrame014.geometry} material={materials['Door_material.011']}>
            <mesh geometry={nodes.Door014.geometry} material={materials['Door_material.011']} position={[0.418, 1.05, 0.022]}>
                <mesh geometry={nodes.Handle_Back013.geometry} material={materials['Handle_material.009']} position={[-0.764, 0, -0.005]} />
                <mesh geometry={nodes.Handle_Front013.geometry} material={materials['Handle_material.009']} position={[-0.764, 0, -0.029]} rotation={[-Math.PI, 0, 0]} />
            </mesh>
            </mesh>
        </group>
        <group position={[-3.096, 0, -8.779]} scale={[0.487, 1, 0.485]}>
            <mesh geometry={nodes.CTRL_Baseboard013.geometry} material={materials['hidden_material.009']} position={[0, -0.1, 0.177]} />
            <mesh geometry={nodes.CTRL_Hole013.geometry} material={materials['hidden_material.009']} position={[0, -0.002, 0.12]} />
            <mesh geometry={nodes.DoorFrame013.geometry} material={materials['Door_material.010']}>
            <mesh geometry={nodes.Door013.geometry} material={materials['Door_material.010']} position={[0.418, 1.05, 0.022]}>
                <mesh geometry={nodes.Handle_Back012.geometry} material={materials['Handle_material.008']} position={[-0.764, 0, -0.005]} />
                <mesh geometry={nodes.Handle_Front012.geometry} material={materials['Handle_material.008']} position={[-0.764, 0, -0.029]} rotation={[-Math.PI, 0, 0]} />
            </mesh>
            </mesh>
        </group>
        <group position={[-4.658, 0, -8.754]} scale={[0.487, 1, 0.485]}>
            <mesh geometry={nodes.CTRL_Baseboard012.geometry} material={materials['hidden_material.008']} position={[0, -0.1, 0.177]} />
            <mesh geometry={nodes.CTRL_Hole012.geometry} material={materials['hidden_material.008']} position={[0, -0.002, 0.12]} />
            <mesh geometry={nodes.DoorFrame012.geometry} material={materials['Door_material.009']}>
            <mesh geometry={nodes.Door012.geometry} material={materials['Door_material.009']} position={[0.418, 1.05, 0.022]}>
                <mesh geometry={nodes.Handle_Back011.geometry} material={materials['Handle_material.007']} position={[-0.764, 0, -0.005]} />
                <mesh geometry={nodes.Handle_Front011.geometry} material={materials['Handle_material.007']} position={[-0.764, 0, -0.029]} rotation={[-Math.PI, 0, 0]} />
            </mesh>
            </mesh>
        </group>
        <group position={[-8.532, 0, 1.61]} rotation={[0, Math.PI / 2, 0]} scale={[0.485, 1, 0.487]}>
            <mesh geometry={nodes.CTRL_Baseboard011.geometry} material={materials['hidden_material.007']} position={[0, -0.1, 0.177]} />
            <mesh geometry={nodes.CTRL_Hole011.geometry} material={materials['hidden_material.007']} position={[0, -0.002, 0.12]} />
            <mesh geometry={nodes.DoorFrame011.geometry} material={materials['Door_material.008']}>
            <mesh geometry={nodes.Door011.geometry} material={materials['Door_material.008']} position={[0.418, 1.05, 0.022]}>
                <mesh geometry={nodes.Handle_Back010.geometry} material={materials['Handle_material.006']} position={[-0.764, 0, -0.005]} />
                <mesh geometry={nodes.Handle_Front010.geometry} material={materials['Handle_material.006']} position={[-0.764, 0, -0.029]} rotation={[-Math.PI, 0, 0]} />
            </mesh>
            </mesh>
        </group>
        <group position={[-13.677, 0, 6.842]} rotation={[0, Math.PI / 2, 0]} scale={[0.485, 1, 0.487]}>
            <mesh geometry={nodes.CTRL_Baseboard010.geometry} material={materials['hidden_material.006']} position={[0, -0.1, 0.177]} />
            <mesh geometry={nodes.CTRL_Hole010.geometry} material={materials['hidden_material.006']} position={[0, -0.002, 0.12]} />
            <mesh geometry={nodes.DoorFrame010.geometry} material={materials['Door_material.007']}>
            <mesh geometry={nodes.Door010.geometry} material={materials['Door_material.007']} position={[0.418, 1.05, 0.022]}>
                <mesh geometry={nodes.Handle_Back009.geometry} material={materials['Handle_material.005']} position={[-0.764, 0, -0.005]} />
                <mesh geometry={nodes.Handle_Front009.geometry} material={materials['Handle_material.005']} position={[-0.764, 0, -0.029]} rotation={[-Math.PI, 0, 0]} />
            </mesh>
            </mesh>
        </group>
        <group position={[-13.659, 0, 8.015]} rotation={[0, Math.PI / 2, 0]} scale={[0.485, 1, 0.487]}>
            <mesh geometry={nodes.CTRL_Baseboard009.geometry} material={materials['hidden_material.005']} position={[0, -0.1, 0.177]} />
            <mesh geometry={nodes.CTRL_Hole009.geometry} material={materials['hidden_material.005']} position={[0, -0.002, 0.12]} />
            <mesh geometry={nodes.DoorFrame009.geometry} material={materials['Door_material.006']}>
            <mesh geometry={nodes.Door009.geometry} material={materials['Door_material.006']} position={[0.418, 1.05, 0.022]}>
                <mesh geometry={nodes.Handle_Back008.geometry} material={materials['Handle_material.004']} position={[-0.764, 0, -0.005]} />
                <mesh geometry={nodes.Handle_Front008.geometry} material={materials['Handle_material.004']} position={[-0.764, 0, -0.029]} rotation={[-Math.PI, 0, 0]} />
            </mesh>
            </mesh>
        </group>
        <group position={[-9.826, 0, 11.24]} scale={[0.487, 1, 0.485]}>
            <mesh geometry={nodes.CTRL_Baseboard006.geometry} material={materials['hidden_material.002']} position={[0, -0.1, 0.177]} />
            <mesh geometry={nodes.CTRL_Hole006.geometry} material={materials['hidden_material.002']} position={[0, -0.002, 0.12]} />
            <mesh geometry={nodes.DoorFrame006.geometry} material={materials['Door_material.003']}>
            <mesh geometry={nodes.Door006.geometry} material={materials['Door_material.003']} position={[0.418, 1.05, 0.022]}>
                <mesh geometry={nodes.Handle_Back005.geometry} material={materials['Handle_material.001']} position={[-0.764, 0, -0.005]} />
                <mesh geometry={nodes.Handle_Front005.geometry} material={materials['Handle_material.001']} position={[-0.764, 0, -0.029]} rotation={[-Math.PI, 0, 0]} />
            </mesh>
            </mesh>
        </group>
        <group position={[-10.791, 0, 11.244]} scale={[0.487, 1, 0.485]}>
            <mesh geometry={nodes.CTRL_Baseboard005.geometry} material={materials['hidden_material.001']} position={[0, -0.1, 0.177]} />
            <mesh geometry={nodes.CTRL_Hole005.geometry} material={materials['hidden_material.001']} position={[0, -0.002, 0.12]} />
            <mesh geometry={nodes.DoorFrame005.geometry} material={materials['Door_material.002']}>
            <mesh geometry={nodes.Door005.geometry} material={materials['Door_material.002']} position={[0.418, 1.05, 0.022]} />
            </mesh>
        </group>
        <group position={[-13.751, 0, 21.12]} rotation={[0, Math.PI / 2, 0]} scale={[0.485, 1, 0.487]}>
            <mesh geometry={nodes.CTRL_Baseboard004.geometry} material={materials.hidden_material} position={[0, -0.1, 0.177]} />
            <mesh geometry={nodes.CTRL_Hole004.geometry} material={materials.hidden_material} position={[0, 0, 0.12]} />
            <mesh geometry={nodes.DoorFrame004.geometry} material={materials.Door_material}>
            <mesh geometry={nodes.Door004.geometry} material={materials.Door_material} position={[0.418, 1.05, 0.022]}>
                <mesh geometry={nodes.Handle_Back004.geometry} material={materials.Handle_material} position={[-0.764, 0, -0.005]} />
                <mesh geometry={nodes.Handle_Front004.geometry} material={materials.Handle_material} position={[-0.764, 0, -0.029]} rotation={[-Math.PI, 0, 0]} />
            </mesh>
            </mesh>
        </group>
        <group position={[-8.532, 0, 1.127]} rotation={[0, Math.PI / 2, 0]} scale={[0.485, 1, 0.487]}>
            <mesh geometry={nodes.CTRL_Baseboard001.geometry} material={materials['hidden_material.027']} position={[0, -0.1, 0.177]} />
            <mesh geometry={nodes.CTRL_Hole001.geometry} material={materials['hidden_material.027']} position={[0, -0.002, 0.12]} />
            <mesh geometry={nodes.DoorFrame001.geometry} material={materials['Door_material.028']}>
            <mesh geometry={nodes.Door001.geometry} material={materials['Door_material.028']} position={[0.418, 1.05, 0.022]}>
                <mesh geometry={nodes.Handle_Back001.geometry} material={materials['Handle_material.026']} position={[-0.764, 0, -0.005]} />
                <mesh geometry={nodes.Handle_Front001.geometry} material={materials['Handle_material.026']} position={[-0.764, 0, -0.029]} rotation={[-Math.PI, 0, 0]} />
            </mesh>
            </mesh>
        </group>
        <group position={[-8.544, 0, 2.093]} rotation={[0, Math.PI / 2, 0]} scale={[0.485, 1, 0.487]}>
            <mesh geometry={nodes.CTRL_Baseboard002.geometry} material={materials['hidden_material.028']} position={[0, -0.1, 0.177]} />
            <mesh geometry={nodes.CTRL_Hole002.geometry} material={materials['hidden_material.028']} position={[0, -0.002, 0.12]} />
            <mesh geometry={nodes.DoorFrame002.geometry} material={materials['Door_material.029']}>
            <mesh geometry={nodes.Door002.geometry} material={materials['Door_material.029']} position={[0.418, 1.05, 0.022]}>
                <mesh geometry={nodes.Handle_Back002.geometry} material={materials['Handle_material.027']} position={[-0.764, 0, -0.005]} />
                <mesh geometry={nodes.Handle_Front002.geometry} material={materials['Handle_material.027']} position={[-0.764, 0, -0.029]} rotation={[-Math.PI, 0, 0]} />
            </mesh>
            </mesh>
        </group>
        <group position={[-8.551, 0, 2.576]} rotation={[0, Math.PI / 2, 0]} scale={[0.485, 1, 0.487]}>
            <mesh geometry={nodes.CTRL_Baseboard003.geometry} material={materials['hidden_material.029']} position={[0, -0.1, 0.177]} />
            <mesh geometry={nodes.CTRL_Hole003.geometry} material={materials['hidden_material.029']} position={[0, -0.002, 0.12]} />
            <mesh geometry={nodes.DoorFrame003.geometry} material={materials['Door_material.030']}>
            <mesh geometry={nodes.Door003.geometry} material={materials['Door_material.030']} position={[0.418, 1.05, 0.022]}>
                <mesh geometry={nodes.Handle_Back003.geometry} material={materials['Handle_material.028']} position={[-0.764, 0, -0.005]} />
                <mesh geometry={nodes.Handle_Front003.geometry} material={materials['Handle_material.028']} position={[-0.764, 0, -0.029]} rotation={[-Math.PI, 0, 0]} />
            </mesh>
            </mesh>
        </group>
        <group position={[-8.557, 0, 3.064]} rotation={[0, Math.PI / 2, 0]} scale={[0.485, 1, 0.487]}>
            <mesh geometry={nodes.CTRL_Baseboard007.geometry} material={materials['hidden_material.030']} position={[0, -0.1, 0.177]} />
            <mesh geometry={nodes.CTRL_Hole007.geometry} material={materials['hidden_material.030']} position={[0, -0.002, 0.12]} />
            <mesh geometry={nodes.DoorFrame007.geometry} material={materials['Door_material.031']}>
            <mesh geometry={nodes.Door007.geometry} material={materials['Door_material.031']} position={[0.418, 1.05, 0.022]}>
                <mesh geometry={nodes.Handle_Back006.geometry} material={materials['Handle_material.029']} position={[-0.764, 0, -0.005]} />
                <mesh geometry={nodes.Handle_Front006.geometry} material={materials['Handle_material.029']} position={[-0.764, 0, -0.029]} rotation={[-Math.PI, 0, 0]} />
            </mesh>
            </mesh>
        </group>
        <group position={[-8.55, 0, 3.547]} rotation={[0, Math.PI / 2, 0]} scale={[0.485, 1, 0.487]}>
            <mesh geometry={nodes.CTRL_Baseboard008.geometry} material={materials['hidden_material.031']} position={[0, -0.1, 0.177]} />
            <mesh geometry={nodes.CTRL_Hole008.geometry} material={materials['hidden_material.031']} position={[0, -0.002, 0.12]} />
            <mesh geometry={nodes.DoorFrame008.geometry} material={materials['Door_material.032']}>
            <mesh geometry={nodes.Door008.geometry} material={materials['Door_material.032']} position={[0.418, 1.05, 0.022]}>
                <mesh geometry={nodes.Handle_Back007.geometry} material={materials['Handle_material.030']} position={[-0.764, 0, -0.005]} />
                <mesh geometry={nodes.Handle_Front007.geometry} material={materials['Handle_material.030']} position={[-0.764, 0, -0.029]} rotation={[-Math.PI, 0, 0]} />
            </mesh>
            </mesh>
        </group>
        <group position={[15.509, 0, 14.305]} scale={[0.487, 1, 0.485]}>
            <mesh geometry={nodes.CTRL_Baseboard016.geometry} material={materials['hidden_material.032']} position={[0, -0.1, 0.177]} />
            <mesh geometry={nodes.CTRL_Hole016.geometry} material={materials['hidden_material.032']} position={[0, -0.002, 0.12]} />
            <mesh geometry={nodes.DoorFrame016.geometry} material={materials['Door_material.033']}>
            <mesh geometry={nodes.Door016.geometry} material={materials['Door_material.033']} position={[0.418, 1.05, 0.022]}>
                <mesh geometry={nodes.Handle_Back015.geometry} material={materials['Handle_material.031']} position={[-0.764, 0, -0.005]} />
                <mesh geometry={nodes.Handle_Front015.geometry} material={materials['Handle_material.031']} position={[-0.764, 0, -0.029]} rotation={[-Math.PI, 0, 0]} />
            </mesh>
            </mesh>
        </group>
        <group position={[18.83, 0, 14.284]} scale={[0.487, 1, 0.485]}>
            <mesh geometry={nodes.CTRL_Baseboard017.geometry} material={materials['hidden_material.033']} position={[0, -0.1, 0.177]} />
            <mesh geometry={nodes.CTRL_Hole017.geometry} material={materials['hidden_material.033']} position={[0, -0.002, 0.12]} />
            <mesh geometry={nodes.DoorFrame017.geometry} material={materials['Door_material.034']}>
            <mesh geometry={nodes.Door017.geometry} material={materials['Door_material.034']} position={[0.418, 1.05, 0.022]}>
                <mesh geometry={nodes.Handle_Back016.geometry} material={materials['Handle_material.032']} position={[-0.764, 0, -0.005]} />
                <mesh geometry={nodes.Handle_Front016.geometry} material={materials['Handle_material.032']} position={[-0.764, 0, -0.029]} rotation={[-Math.PI, 0, 0]} />
            </mesh>
            </mesh>
        </group>
        <group position={[-13.775, 0, 18.742]} rotation={[0, Math.PI / 2, 0]} scale={[0.485, 1, 0.487]}>
            <mesh geometry={nodes.CTRL_Baseboard018.geometry} material={materials['hidden_material.034']} position={[0, -0.1, 0.177]} />
            <mesh geometry={nodes.CTRL_Hole018.geometry} material={materials['hidden_material.034']} position={[0, -0.002, 0.12]} />
            <mesh geometry={nodes.DoorFrame018.geometry} material={materials['Door_material.035']}>
            <mesh geometry={nodes.Door018.geometry} material={materials['Door_material.035']} position={[0.418, 1.05, 0.022]}>
                <mesh geometry={nodes.Handle_Back017.geometry} material={materials['Handle_material.033']} position={[-0.764, 0, -0.005]} />
                <mesh geometry={nodes.Handle_Front017.geometry} material={materials['Handle_material.033']} position={[-0.764, 0, -0.029]} rotation={[-Math.PI, 0, 0]} />
            </mesh>
            </mesh>
        </group>
        <mesh geometry={nodes.Stairs195.geometry} material={materials['Stairs_material.249']} position={[13.148, 2, 19.448]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs192.geometry} material={materials['Stairs_material.246']} position={[13.152, 1.5, 19.879]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs191.geometry} material={materials['Stairs_material.245']} position={[13.151, 1, 20.321]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs183.geometry} material={materials['Stairs_material.233']} position={[14.859, 0, 19.499]} rotation={[Math.PI, 0, Math.PI]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs181.geometry} material={materials['Stairs_material.231']} position={[14.862, 0.5, 19.894]} rotation={[Math.PI, 0, Math.PI]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs152.geometry} material={materials['Stairs_material.194']} position={[-13.529, 0.5, 22.087]} rotation={[Math.PI, 0, Math.PI]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs150.geometry} material={materials['Stairs_material.192']} position={[-11.038, 1, 22.51]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs148.geometry} material={materials['Stairs_material.182']} position={[-14.24, 2, 9.908]} rotation={[0, -Math.PI / 2, 0]} scale={[0.485, 1, 0.487]} />
        <mesh geometry={nodes.Stairs147.geometry} material={materials['Stairs_material.181']} position={[-14.24, 2, 10.194]} rotation={[0, -Math.PI / 2, 0]} scale={[0.485, 1, 0.487]} />
        <mesh geometry={nodes.Stairs146.geometry} material={materials['Stairs_material.180']} position={[-14.687, 1.5, 10.194]} rotation={[0, -Math.PI / 2, 0]} scale={[0.485, 1, 0.487]} />
        <mesh geometry={nodes.Stairs145.geometry} material={materials['Stairs_material.179']} position={[-14.687, 1.5, 9.895]} rotation={[0, -Math.PI / 2, 0]} scale={[0.485, 1, 0.487]} />
        <mesh geometry={nodes.Stairs144.geometry} material={materials['Stairs_material.178']} position={[-15.137, 1, 9.895]} rotation={[0, -Math.PI / 2, 0]} scale={[0.485, 1, 0.487]} />
        <mesh geometry={nodes.Stairs143.geometry} material={materials['Stairs_material.177']} position={[-14.274, 0, 10.685]} rotation={[0, Math.PI / 2, 0]} scale={[0.485, 1, 0.487]} />
        <mesh geometry={nodes.Stairs142.geometry} material={materials['Stairs_material.175']} position={[-14.714, 0.5, 10.681]} rotation={[0, Math.PI / 2, 0]} scale={[0.485, 1, 0.487]} />
        <mesh geometry={nodes.Stairs141.geometry} material={materials['Stairs_material.174']} position={[-14.714, 0.5, 10.869]} rotation={[0, Math.PI / 2, 0]} scale={[0.485, 1, 0.487]} />
        <mesh geometry={nodes.Stairs140.geometry} material={materials['Stairs_material.173']} position={[-14.274, 0, 10.868]} rotation={[0, Math.PI / 2, 0]} scale={[0.485, 1, 0.487]} />
        <mesh geometry={nodes.Stairs139.geometry} material={materials['Stairs_material.190']} position={[-13.529, 0, 21.644]} rotation={[Math.PI, 0, Math.PI]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs134.geometry} material={materials['Stairs_material.185']} position={[-11.038, 1.5, 22.068]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs131.geometry} material={materials['Stairs_material.164']} position={[-15.137, 1, 10.194]} rotation={[0, -Math.PI / 2, 0]} scale={[0.485, 1, 0.487]} />
        <mesh geometry={nodes.Stairs130.geometry} material={materials['Stairs_material.163']} position={[-14.714, 0.5, 10.869]} rotation={[0, Math.PI / 2, 0]} scale={[0.485, 1, 0.487]} />
        <mesh geometry={nodes.Stairs127.geometry} material={materials['Stairs_material.160']} position={[-12.858, 0, -10.574]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs126.geometry} material={materials['Stairs_material.159']} position={[-12.858, 0.5, -11.019]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs117.geometry} material={materials['Stairs_material.150']} position={[-11.234, 1, -11.444]} rotation={[Math.PI, 0, Math.PI]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs115.geometry} material={materials['Stairs_material.148']} position={[-11.234, 1.5, -10.995]} rotation={[Math.PI, 0, Math.PI]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs113.geometry} material={materials['Stairs_material.146']} position={[-11.234, 1, -11.444]} rotation={[Math.PI, 0, Math.PI]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs111.geometry} material={materials['Stairs_material.144']} position={[-11.234, 1.5, -10.995]} rotation={[Math.PI, 0, Math.PI]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs102.geometry} material={materials['Stairs_material.139']} position={[13.74, 1.5, -10.987]} rotation={[Math.PI, 0, Math.PI]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs088.geometry} material={materials['Stairs_material.133']} position={[13.734, 1, -11.436]} rotation={[Math.PI, 0, Math.PI]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs036.geometry} material={materials['Stairs_material.108']} position={[9.847, 0, -10.562]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs025.geometry} material={materials.Stairs_material} position={[9.848, 0.5, -11.007]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Room048.geometry} material={materials.Wall_material} position={[-4.337, 0, -8.745]} rotation={[0, -Math.PI / 2, 0]} scale={[0.485, 1, 0.487]} />
        <mesh geometry={nodes.Room047.geometry} material={materials['Wall_material.001']} position={[-16.781, 0, 7.446]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Room043.geometry} material={materials.Wall_material} position={[-7.487, 0, 6.996]} rotation={[0, Math.PI / 2, 0]} scale={[0.485, 1, 0.487]} />
        <mesh geometry={nodes.Room042.geometry} material={materials['Wall_material.001']} position={[12.91, 0, 18.845]} rotation={[Math.PI / 2, 0, 0]} scale={[0.487, 0.485, 1]} />
        <mesh geometry={nodes.Room041.geometry} material={materials.Wall_material} position={[-7.501, 0, 4.791]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[0.487, 0.485, 1]} />
        <mesh geometry={nodes.Room040.geometry} material={materials.Wall_material} position={[-8.967, 0, 6.96]} rotation={[0, Math.PI / 2, 0]} scale={[0.485, 1, 0.487]} />
        <mesh geometry={nodes.Room038.geometry} material={materials['Material.016']} position={[12.92, 1, 22.474]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.485, 0.487, 1]} />
        <mesh geometry={nodes.Room037.geometry} material={materials.Wall_material} position={[14.198, 0, 21.08]} rotation={[0, Math.PI / 2, 0]} scale={[0.485, 1, 0.487]} />
        <mesh geometry={nodes.Room036.geometry} material={materials.Wall_material} position={[-13.755, 0, 23.407]} rotation={[0, Math.PI / 2, 0]} scale={[0.485, 1, 0.487]} />
        <mesh geometry={nodes.Room034.geometry} material={materials['Material.015']} position={[-13.787, 1, 23.354]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.485, 0.487, 1]} />
        <mesh geometry={nodes.Room033.geometry} material={nodes.Room033.material} position={[-16.781, 1, 9.643]} rotation={[Math.PI / 2, 0, 0]} scale={[0.487, 0.485, 1]} />
        <mesh geometry={nodes.Room032.geometry} material={materials['Wall_material.001']} position={[-15.157, 0, 10.452]} scale={[0.487, 1, 0.485]} />
        {/* <mesh geometry={nodes.Room031.geometry} material={materials['Wall_material.018']} position={[-11.513, 0, -12.599]} rotation={[0, -Math.PI / 2, 0]} scale={[0.485, 1, 0.487]}>
            <mesh geometry={nodes.Baseboard007_1.geometry} material={materials['Baseboard_material.002']} />
        </mesh> */}
        <mesh geometry={nodes.Room030.geometry} material={materials['Wall_material.018']} position={[-13.601, 1, -12.576]} rotation={[Math.PI / 2, 0, 0]} scale={[0.487, 0.485, 1]} />
        <mesh geometry={nodes.Room029.geometry} material={materials.Wall_material} position={[-11.619, 0, -11.546]} rotation={[0, -Math.PI / 2, 0]} scale={[0.485, 1, 0.487]}>
            <mesh geometry={nodes.Baseboard005.geometry} material={materials.Baseboard_material} />
        </mesh>
        <mesh geometry={nodes.Room021.geometry} material={materials.Wall_material} position={[12.992, 0, 22.471]} rotation={[0, Math.PI / 2, 0]} scale={[0.485, 1, 0.487]}>
            <mesh geometry={nodes.Baseboard003.geometry} material={materials.Baseboard_material} />
        </mesh>
        <mesh geometry={nodes.Room020.geometry} material={materials.Wall_material} position={[15.564, 0, 17.827]} rotation={[0, Math.PI / 2, 0]} scale={[0.485, 1, 0.487]} />
        <mesh geometry={nodes.Room019.geometry} material={materials.Wall_material} position={[-8.521, 0, 17.894]} rotation={[0, Math.PI / 2, 0]} scale={[0.485, 1, 0.487]} />
        <mesh geometry={nodes.Room018.geometry} material={materials.Wall_material} position={[-8.517, 2.4, 11.808]} rotation={[Math.PI, Math.PI / 2, 0]} scale={[0.485, 1, 0.487]} />
        <mesh geometry={nodes.Room017.geometry} material={materials['Wall_material.009']} position={[-5.705, 0, -8.745]} rotation={[0, -Math.PI / 2, 0]} scale={[0.485, 1, 0.487]} />
        <mesh geometry={nodes.Room016.geometry} material={materials.Wall_material} position={[-2.238, 0, -8.745]} rotation={[0, -Math.PI / 2, 0]} scale={[0.485, 1, 0.487]}>
            <mesh geometry={nodes.Baseboard004.geometry} material={materials.Baseboard_material} />
        </mesh>
        <mesh geometry={nodes.Room015.geometry} material={materials.Wall_material} position={[-5.668, 0, -6.284]} rotation={[0, Math.PI / 2, 0]} scale={[0.485, 1, 0.487]} />
        <mesh geometry={nodes.Room014.geometry} material={materials['Wall_material.006']} position={[-5.705, 0, -8.75]} rotation={[0, -Math.PI / 2, 0]} scale={[0.485, 1, 0.487]} />
        <mesh geometry={nodes.Room012.geometry} material={materials.Wall_material} position={[13.994, 2.4, -12.596]} rotation={[Math.PI, Math.PI / 2, 0]} scale={[0.485, 1, 0.487]} />
        <mesh geometry={nodes.Room011.geometry} material={materials.Wall_material} position={[-9.182, 2.4, -12.567]} rotation={[Math.PI, Math.PI / 2, 0]} scale={[0.485, 1, 0.487]} />
        <mesh geometry={nodes.Room010.geometry} material={materials.Wall_material} position={[-14.041, 2.4, -12.569]} rotation={[Math.PI, Math.PI / 2, 0]} scale={[0.485, 1, 0.487]} />
        <mesh geometry={nodes.Room009.geometry} material={materials.Wall_material} position={[-14.05, 0, -6.711]} rotation={[0, Math.PI / 2, 0]} scale={[0.485, 1, 0.487]} />
        <mesh geometry={nodes.Room008.geometry} material={materials.Wall_material} position={[-13.763, 0, 4.042]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Room007.geometry} material={materials.Wall_material} position={[-17.197, 0, 9.358]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Room002.geometry} material={materials.Wall_material} position={[-22.471, 0, 20.759]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Room001.geometry} material={materials.Wall_material} position={[-22.468, 0, 19.814]} scale={[0.487, 1, 0.485]}>
            <mesh geometry={nodes.Baseboard.geometry} material={materials.Baseboard_material} />
        </mesh>
        <mesh geometry={nodes.Room.geometry} material={materials.Material} position={[-22.011, 0, 23.343]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Baseboard008.geometry} material={materials['Baseboard_material.001']} position={[-1.527, 0, 2.207]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Room003.geometry} material={materials.Wall_material} position={[-16.751, 0, 19.779]} rotation={[0, Math.PI / 2, 0]} scale={[0.485, 1, 0.487]} />
        <mesh geometry={nodes.Room004.geometry} material={materials.Wall_material} position={[-16.839, 0, 7.38]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Room005.geometry} material={materials.Wall_material} position={[-8.986, 0, 11.133]} rotation={[Math.PI, 0, Math.PI]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Room006.geometry} material={materials.Wall_material} position={[-14.237, 0, -5.289]} rotation={[0, -Math.PI / 2, 0]} scale={[0.485, 1, 0.487]} />
        <mesh geometry={nodes.Room022.geometry} material={materials.Wall_material} position={[-13.768, 0, -6.276]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Room023.geometry} material={materials.Wall_material} position={[4.397, 0, -8.745]} rotation={[0, -Math.PI / 2, 0]} scale={[0.485, 1, 0.487]} />
        <mesh geometry={nodes.Room024.geometry} material={materials.Wall_material} position={[8.867, 0, -8.745]} rotation={[0, -Math.PI / 2, 0]} scale={[0.485, 1, 0.487]} />
        <mesh geometry={nodes.Room025.geometry} material={materials['Wall_material.013']} position={[12.91, 2.4, 18.845]} rotation={[Math.PI / 2, 0, 0]} scale={[0.487, 0.485, 1]} />
        <mesh geometry={nodes.Room026.geometry} material={materials['Wall_material.014']} position={[9.774, 0, 12.079]} rotation={[0, -Math.PI / 2, 0]} scale={[0.485, 1, 0.487]} />
        <mesh geometry={nodes.Room039.geometry} material={materials['Wall_material.016']} position={[7.1, 0, 12.073]} rotation={[0, -Math.PI / 2, 0]} scale={[0.485, 1, 0.487]} />
        <mesh geometry={nodes.Room044.geometry} material={materials.Wall_material} position={[14.745, 0, 12.079]} rotation={[0, -Math.PI / 2, 0]} scale={[0.485, 1, 0.487]} />
        <mesh geometry={nodes.Cabinet1.geometry} material={materials.Cabinet_material} position={[-8.941, 0.139, 15.212]} scale={[0.487, 1, 0.485]}>
            <mesh geometry={nodes.Baseboard1.geometry} material={materials.Baseboard_material} position={[0, -0.16, 0.531]} />
            <mesh geometry={nodes.Cabinet1_Door.geometry} material={materials.Door_material} position={[0.599, 0, 0.591]}>
            <mesh geometry={nodes.Handle.geometry} material={materials.Handle_material} position={[-0.545, 0.576, 0.018]} rotation={[0, 0, -Math.PI / 2]} />
            </mesh>
            <mesh geometry={nodes.Countertop1.geometry} material={materials.countertop_material} position={[0, 0.7, 0]} />
        </mesh>
        <mesh geometry={nodes.Cabinet1001.geometry} material={materials['Cabinet_material.016']} position={[-8.655, 0.139, 15.212]} scale={[0.487, 1, 0.485]}>
            <mesh geometry={nodes.Countertop1001.geometry} material={materials['countertop_material.002']} position={[0, 0.7, 0]} />
        </mesh>
        <mesh geometry={nodes.Cabinet1002.geometry} material={materials['Cabinet_material.018']} position={[-8.357, 0.139, 15.212]} scale={[0.487, 1, 0.485]}>
            <mesh geometry={nodes.Countertop1002.geometry} material={materials['countertop_material.003']} position={[0, 0.7, 0]} />
        </mesh>
        <mesh geometry={nodes.Cabinet1003.geometry} material={materials['Cabinet_material.019']} position={[-8.075, 0.139, 15.212]} scale={[0.487, 1, 0.485]}>
            <mesh geometry={nodes.Countertop1003.geometry} material={materials['countertop_material.004']} position={[0, 0.7, 0]} />
        </mesh>
        <mesh geometry={nodes.Cabinet1004.geometry} material={materials['Cabinet_material.020']} position={[-7.788, 0.139, 15.212]} scale={[0.487, 1, 0.485]}>
            <mesh geometry={nodes.Countertop1004.geometry} material={materials['countertop_material.005']} position={[0, 0.7, 0]} />
        </mesh>
        <mesh geometry={nodes.Cabinet1005.geometry} material={materials['Cabinet_material.021']} position={[-7.515, 0.139, 15.212]} scale={[0.487, 1, 0.485]}>
            <mesh geometry={nodes.Countertop1005.geometry} material={materials['countertop_material.006']} position={[0, 0.7, 0]} />
        </mesh>
        <mesh geometry={nodes.Cabinet1006.geometry} material={materials['Cabinet_material.022']} position={[-7.241, 0.139, 15.212]} scale={[0.487, 1, 0.485]}>
            <mesh geometry={nodes.Countertop1006.geometry} material={materials['countertop_material.007']} position={[0, 0.7, 0]} />
        </mesh>
        <mesh geometry={nodes.Cabinet1007.geometry} material={materials['Cabinet_material.023']} position={[-6.955, 0.139, 15.212]} scale={[0.487, 1, 0.485]}>
            <mesh geometry={nodes.Countertop1007.geometry} material={materials['countertop_material.008']} position={[0, 0.7, 0]} />
        </mesh>
        <mesh geometry={nodes.Cabinet1008.geometry} material={materials['Cabinet_material.024']} position={[-6.677, 0.139, 15.212]} scale={[0.487, 1, 0.485]}>
            <mesh geometry={nodes.Countertop1008.geometry} material={materials['countertop_material.009']} position={[0, 0.7, 0]} />
        </mesh>
        <mesh geometry={nodes.Cabinet1009.geometry} material={materials['Cabinet_material.025']} position={[-6.599, 0.139, 15.212]} scale={[0.487, 1, 0.485]}>
            <mesh geometry={nodes.Countertop1009.geometry} material={materials['countertop_material.010']} position={[0, 0.7, 0]} />
        </mesh>
        <mesh geometry={nodes.Text.geometry} material={materials['Material.002']} position={[-16.561, 3, 8.4]} rotation={[0.803, 0.184, -0.187]} scale={[0.523, 0.792, 0.792]} />
        <mesh geometry={nodes.Text001.geometry} material={materials['Material.003']} position={[-17.676, 3, 2.995]} rotation={[0.803, 0.184, -0.187]} scale={[0.523, 0.792, 0.792]} />
        <mesh geometry={nodes.Text002.geometry} material={materials['Material.001']} position={[-10.178, 4, 9.205]} rotation={[0.803, 0.184, -0.187]} scale={[0.523, 0.792, 0.792]} />
        <mesh geometry={nodes.Text003.geometry} material={materials['Material.004']} position={[-19.13, 3, 21.917]} rotation={[0.803, 0.184, -0.187]} scale={[0.523, 0.792, 0.792]} />
        <mesh geometry={nodes.Text004.geometry} material={materials['Material.005']} position={[-2.895, 4, 16.731]} rotation={[0.803, -0.184, 0.187]} scale={[0.523, 0.792, 0.792]} />
        <mesh geometry={nodes.Text005.geometry} material={materials['Material.006']} position={[0.073, 4, 13.045]} rotation={[0.803, -0.184, 0.187]} scale={[0.523, 0.792, 0.792]} />
        <mesh geometry={nodes.Text006.geometry} material={materials['Material.007']} position={[8.432, 4, 11.213]} rotation={[1.005, -0.245, 0.365]} scale={[0.568, 0.725, 0.87]} />
        <mesh geometry={nodes.Text007.geometry} material={materials['Material.008']} position={[12.708, 4, 13.102]} rotation={[0.803, -0.184, 0.187]} scale={[0.523, 0.792, 0.792]} />
        <mesh geometry={nodes.Text008.geometry} material={materials['Material.009']} position={[17.36, 4, 13.015]} rotation={[0.835, -0.303, 0.319]} scale={[0.568, 0.799, 0.799]} />
        <mesh geometry={nodes.Text009.geometry} material={materials['Material.010']} position={[14.965, 3, 16.254]} rotation={[0.835, -0.303, 0.319]} scale={[0.568, 0.799, 0.799]} />
        <mesh geometry={nodes.Text010.geometry} material={materials['Material.011']} position={[-5.537, 3, -6.882]} rotation={[0.803, 0.184, -0.187]} scale={[0.523, 0.792, 0.792]} />
        <mesh geometry={nodes.Text011.geometry} material={materials['Material.012']} position={[-0.041, 4, -12.11]} rotation={[0.793, -0.123, 0.124]} scale={[0.504, 0.789, 0.789]} />
        <mesh geometry={nodes.Text012.geometry} material={materials['Material.013']} position={[-17.67, 4, -11.423]} rotation={[0.803, 0.184, -0.187]} scale={[0.523, 0.792, 0.792]} />
        <mesh geometry={nodes.Text013.geometry} material={materials['Material.014']} position={[6.823, 4, -7.817]} rotation={[0.793, -0.123, 0.124]} scale={[0.504, 0.789, 0.789]} />
        <mesh geometry={nodes.Stairs001.geometry} material={materials['Stairs_material.001']} position={[-13.337, 0, -10.574]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs002.geometry} material={materials['Stairs_material.002']} position={[-13.337, 0.5, -11.019]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs003.geometry} material={materials['Stairs_material.003']} position={[-12.514, 0, -10.574]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs004.geometry} material={materials['Stairs_material.004']} position={[-12.514, 0.5, -11.019]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs005.geometry} material={materials['Stairs_material.005']} position={[-12.16, 0.5, -11.019]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs006.geometry} material={materials['Stairs_material.006']} position={[-12.16, 0, -10.574]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs007.geometry} material={materials['Stairs_material.007']} position={[-11.837, 0, -10.574]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs008.geometry} material={materials['Stairs_material.008']} position={[-11.837, 0.5, -11.019]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs009.geometry} material={materials['Stairs_material.009']} position={[-10.796, 1, -11.444]} rotation={[Math.PI, 0, Math.PI]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs010.geometry} material={materials['Stairs_material.010']} position={[-10.796, 1.5, -10.995]} rotation={[Math.PI, 0, Math.PI]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs011.geometry} material={materials['Stairs_material.011']} position={[-10.796, 1, -11.444]} rotation={[Math.PI, 0, Math.PI]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs012.geometry} material={materials['Stairs_material.012']} position={[-10.796, 1.5, -10.995]} rotation={[Math.PI, 0, Math.PI]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs013.geometry} material={materials['Stairs_material.013']} position={[-10.39, 1.5, -10.995]} rotation={[Math.PI, 0, Math.PI]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs014.geometry} material={materials['Stairs_material.014']} position={[-10.39, 1, -11.444]} rotation={[Math.PI, 0, Math.PI]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs015.geometry} material={materials['Stairs_material.015']} position={[-10.39, 1.5, -10.995]} rotation={[Math.PI, 0, Math.PI]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs016.geometry} material={materials['Stairs_material.016']} position={[-10.39, 1, -11.444]} rotation={[Math.PI, 0, Math.PI]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs017.geometry} material={materials['Stairs_material.017']} position={[-10.009, 1, -11.444]} rotation={[Math.PI, 0, Math.PI]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs018.geometry} material={materials['Stairs_material.018']} position={[-10.009, 1.5, -10.995]} rotation={[Math.PI, 0, Math.PI]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs019.geometry} material={materials['Stairs_material.019']} position={[-10.009, 1, -11.444]} rotation={[Math.PI, 0, Math.PI]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs020.geometry} material={materials['Stairs_material.020']} position={[-10.009, 1.5, -10.995]} rotation={[Math.PI, 0, Math.PI]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs021.geometry} material={materials['Stairs_material.021']} position={[-9.859, 1.5, -10.995]} rotation={[Math.PI, 0, Math.PI]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs022.geometry} material={materials['Stairs_material.022']} position={[-9.859, 1, -11.444]} rotation={[Math.PI, 0, Math.PI]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs023.geometry} material={materials['Stairs_material.023']} position={[-9.859, 1.5, -10.995]} rotation={[Math.PI, 0, Math.PI]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs024.geometry} material={materials['Stairs_material.024']} position={[-9.859, 1, -11.444]} rotation={[Math.PI, 0, Math.PI]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs026.geometry} material={materials['Stairs_material.025']} position={[10.33, 0, -10.64]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs027.geometry} material={materials['Stairs_material.026']} position={[10.33, 0.5, -11.085]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs028.geometry} material={materials['Stairs_material.027']} position={[11.954, 1, -11.511]} rotation={[Math.PI, 0, Math.PI]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs029.geometry} material={materials['Stairs_material.028']} position={[11.954, 1.5, -11.062]} rotation={[Math.PI, 0, Math.PI]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs030.geometry} material={materials['Stairs_material.029']} position={[11.954, 1, -11.511]} rotation={[Math.PI, 0, Math.PI]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs031.geometry} material={materials['Stairs_material.030']} position={[11.954, 1.5, -11.062]} rotation={[Math.PI, 0, Math.PI]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs032.geometry} material={materials['Stairs_material.031']} position={[13.33, 1, -11.511]} rotation={[Math.PI, 0, Math.PI]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs033.geometry} material={materials['Stairs_material.032']} position={[13.33, 1.5, -11.062]} rotation={[Math.PI, 0, Math.PI]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs034.geometry} material={materials['Stairs_material.033']} position={[13.33, 1, -11.511]} rotation={[Math.PI, 0, Math.PI]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs035.geometry} material={materials['Stairs_material.034']} position={[13.33, 1.5, -11.062]} rotation={[Math.PI, 0, Math.PI]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs037.geometry} material={materials['Stairs_material.035']} position={[13.18, 1.5, -11.062]} rotation={[Math.PI, 0, Math.PI]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs038.geometry} material={materials['Stairs_material.036']} position={[13.18, 1, -11.511]} rotation={[Math.PI, 0, Math.PI]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs039.geometry} material={materials['Stairs_material.037']} position={[13.18, 1.5, -11.062]} rotation={[Math.PI, 0, Math.PI]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs040.geometry} material={materials['Stairs_material.038']} position={[13.18, 1, -11.511]} rotation={[Math.PI, 0, Math.PI]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs041.geometry} material={materials['Stairs_material.039']} position={[12.798, 1, -11.511]} rotation={[Math.PI, 0, Math.PI]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs042.geometry} material={materials['Stairs_material.040']} position={[12.798, 1.5, -11.062]} rotation={[Math.PI, 0, Math.PI]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs043.geometry} material={materials['Stairs_material.041']} position={[12.798, 1, -11.511]} rotation={[Math.PI, 0, Math.PI]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs044.geometry} material={materials['Stairs_material.042']} position={[12.798, 1.5, -11.062]} rotation={[Math.PI, 0, Math.PI]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs045.geometry} material={materials['Stairs_material.043']} position={[12.392, 1.5, -11.062]} rotation={[Math.PI, 0, Math.PI]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs046.geometry} material={materials['Stairs_material.044']} position={[12.392, 1, -11.511]} rotation={[Math.PI, 0, Math.PI]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs047.geometry} material={materials['Stairs_material.045']} position={[12.392, 1.5, -11.062]} rotation={[Math.PI, 0, Math.PI]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs048.geometry} material={materials['Stairs_material.046']} position={[12.392, 1, -11.511]} rotation={[Math.PI, 0, Math.PI]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs049.geometry} material={materials['Stairs_material.047']} position={[11.351, 0.5, -11.085]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs050.geometry} material={materials['Stairs_material.048']} position={[11.351, 0, -10.64]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs051.geometry} material={materials['Stairs_material.049']} position={[11.028, 0, -10.64]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs052.geometry} material={materials['Stairs_material.050']} position={[11.028, 0.5, -11.085]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs053.geometry} material={materials['Stairs_material.051']} position={[10.674, 0.5, -11.085]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs054.geometry} material={materials['Stairs_material.052']} position={[10.674, 0, -10.64]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs055.geometry} material={materials['Stairs_material.053']} position={[9.851, 0.5, -11.085]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs056.geometry} material={materials['Stairs_material.054']} position={[9.851, 0, -10.64]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Room013.geometry} material={materials['Wall_material.002']} position={[11.676, 0, -12.666]} rotation={[0, -Math.PI / 2, 0]} scale={[0.485, 1, 0.487]}>
            <mesh geometry={nodes.Baseboard001.geometry} material={materials['Baseboard_material.003']} />
        </mesh>
        <mesh geometry={nodes.Room027.geometry} material={materials['Wall_material.002']} position={[9.587, 1, -12.643]} rotation={[Math.PI / 2, 0, 0]} scale={[0.487, 0.485, 1]} />
        <mesh geometry={nodes.Room028.geometry} material={materials['Wall_material.003']} position={[11.569, 0, -11.613]} rotation={[0, -Math.PI / 2, 0]} scale={[0.485, 1, 0.487]}>
            <mesh geometry={nodes.Baseboard002.geometry} material={materials['Baseboard_material.004']} />
        </mesh>
        <mesh geometry={nodes.Room045.geometry} material={materials.Wall_material} position={[-11.151, 0, 22.683]} rotation={[0, Math.PI / 2, 0]} scale={[0.485, 1, 0.487]} />
        <mesh geometry={nodes.Stairs057.geometry} material={materials['Stairs_material.055']} position={[-13.092, 0.5, 22.087]} rotation={[Math.PI, 0, Math.PI]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs058.geometry} material={materials['Stairs_material.056']} position={[-13.091, 0, 21.644]} rotation={[Math.PI, 0, Math.PI]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs059.geometry} material={materials['Stairs_material.057']} position={[-12.716, 0, 21.644]} rotation={[Math.PI, 0, Math.PI]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs060.geometry} material={materials['Stairs_material.058']} position={[-12.717, 0.5, 22.087]} rotation={[Math.PI, 0, Math.PI]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs061.geometry} material={materials['Stairs_material.059']} position={[-12.368, 0.5, 22.087]} rotation={[Math.PI, 0, Math.PI]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs062.geometry} material={materials['Stairs_material.060']} position={[-12.367, 0, 21.644]} rotation={[Math.PI, 0, Math.PI]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs063.geometry} material={materials['Stairs_material.061']} position={[-12.08, 0, 21.644]} rotation={[Math.PI, 0, Math.PI]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs064.geometry} material={materials['Stairs_material.062']} position={[-12.081, 0.5, 22.087]} rotation={[Math.PI, 0, Math.PI]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs065.geometry} material={materials['Stairs_material.063']} position={[-11.774, 0.5, 22.087]} rotation={[Math.PI, 0, Math.PI]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs066.geometry} material={materials['Stairs_material.064']} position={[-11.773, 0, 21.644]} rotation={[Math.PI, 0, Math.PI]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs067.geometry} material={materials['Stairs_material.065']} position={[-11.57, 0, 21.644]} rotation={[Math.PI, 0, Math.PI]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs068.geometry} material={materials['Stairs_material.066']} position={[-11.57, 0.5, 22.087]} rotation={[Math.PI, 0, Math.PI]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs069.geometry} material={materials['Stairs_material.067']} position={[-10.627, 1, 22.51]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs070.geometry} material={materials['Stairs_material.068']} position={[-10.626, 1.5, 22.068]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs071.geometry} material={materials['Stairs_material.069']} position={[-10.282, 1.5, 22.068]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs072.geometry} material={materials['Stairs_material.070']} position={[-10.283, 1, 22.51]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs073.geometry} material={materials['Stairs_material.071']} position={[-9.996, 1, 22.51]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs074.geometry} material={materials['Stairs_material.072']} position={[-9.996, 1.5, 22.068]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs075.geometry} material={materials['Stairs_material.073']} position={[-9.683, 1.5, 22.068]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs076.geometry} material={materials['Stairs_material.074']} position={[-9.684, 1, 22.51]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs077.geometry} material={materials['Stairs_material.075']} position={[-9.465, 1, 22.51]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs078.geometry} material={materials['Stairs_material.076']} position={[-9.464, 1.5, 22.068]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs079.geometry} material={materials['Stairs_material.077']} position={[-9.204, 1.5, 22.068]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs080.geometry} material={materials['Stairs_material.078']} position={[-9.204, 1, 22.51]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs081.geometry} material={materials['Stairs_material.079']} position={[13.508, 2, 19.448]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs082.geometry} material={materials['Stairs_material.080']} position={[13.512, 1.5, 19.879]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs083.geometry} material={materials['Stairs_material.081']} position={[13.511, 1, 20.321]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs084.geometry} material={materials['Stairs_material.082']} position={[13.751, 1, 20.321]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs085.geometry} material={materials['Stairs_material.083']} position={[13.751, 1.5, 19.879]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs086.geometry} material={materials['Stairs_material.084']} position={[13.747, 2, 19.448]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs087.geometry} material={materials['Stairs_material.085']} position={[14.531, 0, 19.499]} rotation={[Math.PI, 0, Math.PI]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs089.geometry} material={materials['Stairs_material.086']} position={[14.533, 0.5, 19.894]} rotation={[Math.PI, 0, Math.PI]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs090.geometry} material={materials['Stairs_material.087']} position={[14.356, 0.5, 19.894]} rotation={[Math.PI, 0, Math.PI]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Stairs091.geometry} material={materials['Stairs_material.088']} position={[14.354, 0, 19.499]} rotation={[Math.PI, 0, Math.PI]} scale={[0.487, 1, 0.485]} />
        <mesh geometry={nodes.Plane.geometry} material={materials['Material.017']} position={[-0.048, 0, 4.419]} scale={[25, 1, 20]} />
            </group>
        {
            (pointAp2 != null && pointBp2 != null) && (
                pts.map(p => (
                <RutaMap key={p.id} point1={point[p.a].posicion} point2={point[p.b].posicion} />
                ))
            )
        }
            {/* <RutaMap point1={point[0].posicion} point2={point[1].posicion} /> */}

            {/* <RutaMap point1={point[0].posicion} point2={point[4].posicion} />
            <RutaMap point1={point[4].posicion} point2={point[5].posicion} />

            <RutaMap point1={point[5].posicion} point2={point[1].posicion} />
            <RutaMap point1={point[6].posicion} point2={point[2].posicion} />
            <RutaMap point1={point[6].posicion} point2={point[5].posicion} />

            <RutaMap point1={point[7].posicion} point2={point[4].posicion} />
            <RutaMap point1={point[8].posicion} point2={point[7].posicion} />
            <RutaMap point1={point[8].posicion} point2={point[3].posicion} /> */}

            {/* <RutaMap point1={point[3].posicion} point2={point[4].posicion} /> */}
        </>
    )
}

useGLTF.preload('/piso2_fisi_final.glb')

